import { z } from 'zod'

/**
 * AuthoringPlan: the deterministic, machine-executable instruction set the
 * Playwright author consumes. Generated by translator.ts from a PageContent.
 *
 * The shape is mirrored in skills/loop-playbook-migration/SKILL.md so the LLM
 * has a single source of truth.
 */

export const HeadingBlockSchema = z.object({
  type: z.literal('heading'),
  level: z.union([z.literal(2), z.literal(3)]),
  text: z.string().min(1),
})

export const TextBlockSchema = z.object({
  type: z.literal('text'),
  markdown: z.string().min(1),
})

export const ImageBlockSchema = z.object({
  type: z.literal('image'),
  localPath: z.string().min(1),
  layout: z.union([z.literal('full'), z.literal('inline')]),
  alt: z.string().min(1),
  caption: z.string().optional(),
})

export const DividerBlockSchema = z.object({
  type: z.literal('divider'),
})

export const EmbedBlockSchema = z.object({
  type: z.literal('embed'),
  url: z.string().url(),
  provider: z.union([
    z.literal('youtube'),
    z.literal('vimeo'),
    z.literal('stream'),
    z.literal('other'),
  ]),
  title: z.string().optional(),
})

export const CalloutBlockSchema = z.object({
  type: z.literal('callout'),
  style: z.union([z.literal('info'), z.literal('warning'), z.literal('tip')]),
  markdown: z.string().min(1),
})

// twoColumn is recursive; declare it after the leaves with z.lazy.
export type PlanBlock =
  | z.infer<typeof HeadingBlockSchema>
  | z.infer<typeof TextBlockSchema>
  | z.infer<typeof ImageBlockSchema>
  | z.infer<typeof DividerBlockSchema>
  | z.infer<typeof EmbedBlockSchema>
  | z.infer<typeof CalloutBlockSchema>
  | { type: 'twoColumn'; left: PlanBlock[]; right: PlanBlock[] }

export const PlanBlockSchema: z.ZodType<PlanBlock> = z.lazy(() =>
  z.discriminatedUnion('type', [
    HeadingBlockSchema,
    TextBlockSchema,
    ImageBlockSchema,
    DividerBlockSchema,
    EmbedBlockSchema,
    CalloutBlockSchema,
    z.object({
      type: z.literal('twoColumn'),
      left: z.array(PlanBlockSchema),
      right: z.array(PlanBlockSchema),
    }),
  ]),
)

export const ManualOverrideSchema = z.object({
  /** 0-based index into `blocks`. -1 means "before the first block". */
  afterBlockIndex: z.number().int().min(-1),
  reason: z.string().min(1),
})

export const AuthoringPlanSchema = z.object({
  title: z.string().min(1),
  slug: z.string().min(1),
  blocks: z.array(PlanBlockSchema),
  manualOverrides: z.array(ManualOverrideSchema),
  warnings: z.array(z.string()),
})

export type AuthoringPlan = z.infer<typeof AuthoringPlanSchema>
export type ManualOverride = z.infer<typeof ManualOverrideSchema>
